[package]
name = "sensor_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-modbus = "0.6"
tokio-serial = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
